#!/usr/bin/env python3


import os
import shutil

from module_scripts.web_download import *
from module_scripts.config import *
from module_scripts.apt import *
from module_scripts.write_main_playbook import *
from module_scripts.write_config import *
from module_scripts.write_hosts import *
from module_scripts.git import *
from module_scripts.copy import *
from module_scripts.service import *
from module_scripts.file import *
from module_scripts.web_download import * 
from module_scripts.general_functions import *
from module_scripts.unarchive import *

# delete existing ansible workspace if one exists
try:
    shutil.rmtree(cwd + '/playbook')
except:
    pass

# create ansible directory stucture
os.mkdir( cwd + "/playbook" )
os.mkdir( cwd + "/playbook/source" )
os.mkdir( cwd + "/playbook/roles" )
os.mkdir( cwd + "/playbook/roles/main" )
os.mkdir( cwd + "/playbook/roles/main/tasks" )

# create playbook and config files
create_playbook(cwd)
create_config(cwd)
create_hosts(cwd)

# write main role

# prefix
file_object = open(cwd + "/playbook/roles/main/tasks/main.yml", "a+")
file_object.write("---\n")
file_object.write("\n")
file_object.close()

apt(lines,cwd)
git_clone(lines,cwd)
wget(lines,cwd)
curl(lines,cwd)
tar(lines,cwd)

copy_config(lines,cwd)
file_set_permissions_chmod(lines,cwd)
file_set_permissions_chown(lines,cwd)
service_systemctl(lines,cwd)

# postfix
file_object = open(cwd + "/playbook/roles/main/tasks/main.yml", "a+")
file_object.write("...")
file_object.close()

