---

- name: install dependencies
  apt:
    name:
      - ansible
      - tigervnc-standalone-server
    state: latest

- name: clone needed git repos
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    force: yes
  with_items:
     - { src: "https://poop", dest: "/test/location" }
     - { src: "ssh:thing1", dest: "." }
     - { src: "https://test/repo", dest: "andrew/stuff" }

---